### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by SaintMortum** [zerobig/vscode-1c-metadata-viewer#7]
Возможно, из-за того что линукс.
Возникает при попытке открыть любой модуль.

Error running command metadataViewer.openForm: [UriError]: If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//"). This is likely caused by the extension that contributes metadataViewer.openForm.

**Comment by zerobig** [comment]
Эта ошибка не забыта. Работа над ней идёт. Правда работа пока зависла на этапе: "...где бы мне получить доступ к Linux с GUI?" Если по этому поводу есть идеи, то предлагайте. Виртуалку развернуть для меня к сожалению не вариант.

**Comment by nixel2007** [comment]
@zerobig докер работает? Если да, то могу дать контейнер с vnc и xfce

**Comment by nixel2007** [comment]
Ещё вот такая штука есть

https://www.onworks.net/runos/create-os.html

**Comment by zerobig** [comment]
Внёс правку d3431585e133276abd638402ed1c9696f5221c1c
Должно заработать. Последний тест не успел проверить из-за отсутствия русской локали на той Ubuntu, на которой тестировал.
Войдёт в версию 0.0.7. Ещё несколько изменений и выпущу.

**Comment by mothlike** [comment]
В macOS та же проблема:
`2022-11-07 11:44:01.359 [error] Error: [UriError]: If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//")
	at T (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:64:18444)
	at new _ (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:64:19352)
	at new h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:64:20733)
	at _.parse (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:64:19844)
	at OpenFile (/Users/mothlike/.vscode/extensions/zerobig.vscode-1c-metadata-viewer-0.0.6/out/extension.js:57:33)
	at /Users/mothlike/.vscode/extensions/zerobig.vscode-1c-metadata-viewer-0.0.6/out/extension.js:35:9
	at s._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:92:111375)
	at s.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:92:112079)
	at l._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:13680)
	at l._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:13362)
	at l._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:12132)
	at l._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:11033)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:8941
	at h.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at v.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at g.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at r.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:70:16515)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:17104
	at h.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at v.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at g.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at r.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:70:16515)
	at o._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:70:21327)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:70:18770
	at h.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at v.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at g.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at g.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:70:13346)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:70:12476
	at Socket.i (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:70:24594)
	at Socket.emit (node:events:526:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Readable.push (node:internal/streams/readable:228:10)
	at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) metadataViewer.openModule {"value":"zerobig.vscode-1c-metadata-viewer","_lower":"zerobig.vscode-1c-metadata-viewer"}`

**Comment by zerobig** [comment]
Выпустил релиз. Проверьте пожалуйста исправилась ли ошибка?

**Comment by mothlike** [comment]
В macOS заработало, спасибо. Теперь ждем открытия модулей по двойному клику, чтобы жизнь стала прекрасной )

**Comment by SaintMortum** [comment]
Спасибо. Теперь работает.
